"""
Alpaca PySpark Connector

A PySpark connector for fetching historical stock bars from the Alpaca API
with distributed computation capabilities.

Author: Generated by Claude
License: MIT
"""

from .alpaca_connector import AlpacaHistoricalBarsConnector, create_connector

__version__ = "1.0.0"
__all__ = ["AlpacaHistoricalBarsConnector", "create_connector"]